routes/web.php
Route::post('/store', 'Web\HomeController@store')->name('store');

Route::post('load/category', 'Web\HomeController@loadcategory')->name('load.category');

Route::post('load/featureandcategoryforcategorypage', 'Web\CategoryController@loadfeatureandcategoryforcategorypage')->name('load.featureandcategoryforcategorypage');

Route::post('load/product', 'Web\CategoryController@loadproduct')->name('load.product');

Route::post('load/filter/product', 'Web\CategoryController@loadfilterproduct')->name('load.filter.product');

Route::get('/product/{product_slug}', 'Web\ProductController@index')->name('product');

Route::post('load/productbylcation', 'Web\ProductController@loadproductbylcation')->name('load.productbylcation');

Route::post('load/offerebysort', 'Web\ProductController@loadofferebysort')->name('load.offerebysort');

Route::post('load/offerebyfilter', 'Web\ProductController@loadofferebyfilter')->name('load.offerebyfilter');

Route::post('load/moreoffere', 'Web\ProductController@loadmoreoffere')->name('load.moreoffere');

Route::get('/signup', 'Web\RegisterController@index')->name('signup');

Route::get('/login', 'Web\LoginController@index')->name('web.login');

Route::post('/login/login', 'Web\LoginController@login')->name('web.login.login');

Route::post('/login/loginbyemail', 'Web\LoginController@loginbyemail')->name('web.login.loginbyemail');

Route::post('/login/logout', 'Web\LoginController@logout')->name('web.login.logout');

Route::get('/brand/{brand_slug}', 'Web\BrandController@index')->name('brand');

Route::post('load/featureandbrandforbrandpage', 'Web\BrandController@loadfeatureandbrandforbrandpage')->name('load.featureandbrandforbrandpage');

Route::post('load/brandwiseproduct', 'Web\BrandController@loadbrandwiseproduct')->name('load.brandwiseproduct');

Route::post('adddeletewishlist', 'Web\WishListController@adddeletewishlist')->name('adddeletewishlist');

Route::get('/subcategory/{subcategory_slug}', 'Web\SubCategoryController@index')->name('subcategory');

Route::post('load/featureandproductforsubcategorypage', 'Web\SubCategoryController@loadfeatureandproductforsubcategorypage')->name('load.featureandproductforsubcategorypage');

Route::post('load/subcategory/product', 'Web\SubCategoryController@loadsubcategoryproduct')->name('load.subcategory.product');

Route::post('load/subcategory/filter/product', 'Web\SubCategoryController@loadsubcategoryfilterproduct')->name('load.subcategory.filter.product');

Route::get('/dashboard', 'Web\DashboardController@index')->name('web.dashboard');

Route::get('/vendor/{id}', 'Web\VendorController@index')->name('web.vendor');

Route::post('load/featureandproductforvendorpage', 'Web\VendorController@loadfeatureandproductforvendorpage')->name('load.featureandproductforvendorpage');

Route::post('load/vendorwiseproduct', 'Web\VendorController@loadvendorwiseproduct')->name('load.vendorwiseproduct');

Route::get('/search/{search_slug}', 'Web\SearchController@index')->name('web.search');

Route::post('load/featureandproductforsearchpage', 'Web\SearchController@loadfeatureandproductforsearchpage')->name('load.featureandproductforsearchpage');

Route::post('load/searchwiseproduct', 'Web\SearchController@loadsearchwiseproduct')->name('load.searchwiseproduct');

Route::post('getroute', 'Web\HomeController@getroute')->name('getroute');

Route::post('order', 'Web\ProductController@order')->name('order');

Route::post('web/sendotp', 'Web\RegisterController@sendotp')->name('web.sendotp');

Route::post('web/checkotp', 'Web\RegisterController@checkotp')->name('web.checkotp');

Route::post('web/customerregistration', 'Web\RegisterController@customerregistration')->name('web.customerregistration');

Route::post('web/subarea', 'Web\RegisterController@subarea')->name('web.subarea');

Route::get('web/contact-us', 'Web\HomeController@contactus')->name('web.contactus');

Route::get('web/about-us', 'Web\HomeController@aboutus')->name('web.aboutus');

Route::get('web/faq', 'Web\HomeController@faq')->name('web.faq');

Route::get('web/privacy-policy', 'Web\HomeController@privacy')->name('web.privacy-policy');

Route::get('web/term-conditions', 'Web\HomeController@termandcondition')->name('web.term-conditions');

Route::get('web/why-buy-from-us', 'Web\HomeController@whybuyfromus')->name('web.why-buy-from-us');

Route::post('web/customerprofileupdate', 'Web\RegisterController@customerprofileupdate')->name('web.customerprofileupdate');

Route::get('/forget', 'Web\ForgetController@index')->name('web.forget');

Route::post('web/forget/sendotp', 'Web\ForgetController@forgetsendotp')->name('web.forget.sendotp');

Route::post('web/.forget/checkotp', 'Web\ForgetController@forgetcheckotp')->name('web.forget.checkotp');

Route::post('web/forget/password', 'Web\ForgetController@customerforgetPassword')->name('web.forget.customerforgetPassword');

Route::get('web/contact-us', 'Web\ContactUsController@contactus')->name('web.contactus');

Route::post('web/contact-us/send', 'Web\ContactUsController@store')->name('web.contactus.send');

Route::get('admin/', function () {
    return view('auth.login');
});
Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
});



//Auth::routes();
Route::get('auth/redirect/{provider}', 'Auth\FacebookLoginController@redirect');
Route::get('callback/{provider}', 'Auth\FacebookLoginController@callback');

Route::post('/sendOTP', 'Auth\LoginController@sendOTP')->name('sendOTP');

Route::middleware(['auth','disablepreventback'])->group(function () {
    
 Route::get('admin/home', 'Admin\DashboardController@index')->name('home');

  Route::resource('/admin/brand', 'Admin\BrandController', [ 'names' => [
            'index'    => 'admin.brand.index',
            'create'   => 'admin.brand.create',
            'store'    => 'admin.brand.store',
            'edit'     => 'admin.brand.edit',
            'update'   => 'admin.brand.update',
            'destroy'  => 'admin.brand.destroy',
        ]
    ]);

  Route::resource('/admin/InfoGraphic', 'Admin\InfoGraphicController', [ 'names' => [
            'index'    => 'admin.InfoGraphic.index',
            'create'   => 'admin.InfoGraphic.create',
            'store'    => 'admin.InfoGraphic.store',
            'edit'     => 'admin.InfoGraphic.edit',
            'update'   => 'admin.InfoGraphic.update',
            'destroy'  => 'admin.InfoGraphic.destroy',
        ]
    ]);

  Route::resource('/admin/ads', 'Admin\AdsController', [ 'names' => [
            'index'    => 'admin.ads.index',
            'create'   => 'admin.ads.create',
            'store'    => 'admin.ads.store',
            'edit'     => 'admin.ads.edit',
            'update'   => 'admin.ads.update',
            'destroy'  => 'admin.ads.destroy',
        ]
    ]);

  Route::resource('/admin/categories', 'Admin\CategoryController', [ 'names' => [
            'index'    => 'admin.categories.index',
            'create'   => 'admin.categories.create',
            'store'    => 'admin.categories.store',
            'edit'     => 'admin.categories.edit',
            'update'   => 'admin.categories.update',
            'destroy'  => 'admin.categories.destroy',
        ]
    ]);

  Route::resource('/admin/subcategories', 'Admin\SubCategoryController', [ 'names' => [
            'index'    => 'admin.subcategories.index',
            'create'   => 'admin.subcategories.create',
            'store'    => 'admin.subcategories.store',
            'edit'     => 'admin.subcategories.edit',
            'update'   => 'admin.subcategories.update',
            'destroy'  => 'admin.subcategories.destroy',
        ]
    ]);

  Route::resource('/admin/product', 'Admin\ProductController', [ 'names' => [
            'index'    => 'admin.product.index',
            'create'   => 'admin.product.create',
            'store'    => 'admin.product.store',
            'edit'     => 'admin.product.edit',
            'update'   => 'admin.product.update',
            'destroy'  => 'admin.product.destroy',
        ]
    ]);
  Route::post('/subcategorybyid', 'Admin\ProductController@subcategorybyid')->name('subcategorybyid');
  Route::post('/keyfeaturebysubid', 'Admin\ProductController@keyfeaturebysubid')->name('keyfeaturebysubid');
  Route::post('/deletegalleryimage', 'Admin\ProductController@deletegalleryimage')->name('deletegalleryimage');
  Route::post('/changenewarrival', 'Admin\ProductController@changenewarrival')->name('changenewarrival');
  Route::post('/changehotproduct', 'Admin\ProductController@changehotproduct')->name('changehotproduct');

  Route::resource('/admin/keyfeature', 'Admin\KeyFeatureController', [ 'names' => [
            'index'    => 'admin.keyfeature.index',
            'create'   => 'admin.keyfeature.create',
            'store'    => 'admin.keyfeature.store',
            'edit'     => 'admin.keyfeature.edit',
            'update'   => 'admin.keyfeature.update',
            'destroy'  => 'admin.keyfeature.destroy',
        ]
    ]);

  Route::resource('/admin/package', 'Admin\PackageController', [ 'names' => [
            'index'    => 'admin.package.index',
            'create'   => 'admin.package.create',
            'store'    => 'admin.package.store',
            'edit'     => 'admin.package.edit',
            'update'   => 'admin.package.update',
            'destroy'  => 'admin.package.destroy',
        ]
    ]);

  Route::resource('/admin/cms', 'Admin\CMSController', [ 'names' => [
            'index'    => 'admin.cms.index',
            'create'   => 'admin.cms.create',
            'store'    => 'admin.cms.store',
            'edit'     => 'admin.cms.edit',
            'update'   => 'admin.cms.update',
            'destroy'  => 'admin.cms.destroy',
        ]
    ]);

    Route::resource('/admin/owner', 'Admin\ProfileController', [ 'names' => [
        'index'    => 'admin.owner.index',
        'create'   => 'admin.owner.create',
        'store'    => 'admin.owner.store',
        'edit'     => 'admin.owner.edit',

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    public function Customer()
    {
        return $this->belongsTo(Customer::class,'customer_id');
    }
    public function Product()
    {
        return $this->belongsTo(Product::class,'product_id');
    }

    public function getProduct()
    {
        return $this->Product()->with(['ProductImage'])->withTrashed();
    }

    public function OffereDetail()
    {
        return $this->belongsTo(OffereDetail::class,'offere_id');
    }
}

app/Vendor.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vendor extends Model
{
    use SoftDeletes;
    public function SubCatagory()
    {
        return $this->belongsToMany(SubCatagory::class, 'sub_catagories','vendor_id','sub_catagory_id');
    }

    public function SubArea()
    {
        return $this->belongsToMany(SubArea::class, 'vendor_sub_areas','vendor_id','sub_area_id');
    }

    public function Product()
    {
        return $this->belongsToMany(Product::class, 'ofere_masters','product_id','vendor_id');
    }

    public function Package()
    {
        return $this->belongsToMany(Package::class, 'vendor_packages','package_id','vendor_id');
    }

    public function packagehistory()
    {
        return $this->belongsToMany(Package::class, 'package_histories','package_id','vendor_id');
    }

    public function getPicturePathAttribute($path)
    {
        if($path){
        return asset(str_replace('public/', 'storage/', $path));
        }
        else{
            return null;
        }
    }
    public function getCnicFrontImgPathAttribute($path)
    {
        if($path){
            return asset(str_replace('public/', 'storage/', $path));
            }
            else{
                return null;
            }
    }

    public function getCnicBackImgPathAttribute($path)
    {
        if($path){
            return asset(str_replace('public/', 'storage/', $path));
            }
            else{
                return null;
            }
    }
    public function user()
    {
       return $this->belongsTo(User::Class,'user_id','id')->withTrashed();
    }


    public function GiveoffereMaster()
    {
        return $this->hasMany(GiveOffereMaster::class);
    }
}

app/Http/Controllers/API/ProductDetail/OrderController.php
<?php

namespace App\Http\Controllers\API\ProductDetail;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Order;
use App\OffereDetail;
use App\GiveOffereDetail;
use Auth;
class OrderController extends Controller
{

  public function getallorder()
    {
      $get_order_history    = Order::with(['OffereDetail.OffereMaster.Vendor','OffereDetail.OffereMaster.Product'])->where('customer_id',Auth::user()->userType->id)->get();
      return response()->json([
        'get_order_history'    => $get_order_history
         ]);
    }

  public function addorder(Request $request){
    $request->validate([
           'offere_id'       => 'required',
       ]);
      $CurrentDate=date('Y-m-d');
      $customer_id =0;
      $status = false;
      $errMsg= '';
      $check_order = Order::where('customer_id',Auth::user()->userType->id)->where('offere_id',$request->offere_id)->first();
      if($check_order){
          $status = false;
          $errMsg= 'Already order Saved';
      } 
      else{
        $get_offere_detail_for_cash = GiveOffereDetail::where('offere_id',$request->offere_id)->first();
        $get_offere_detail = OffereDetail::with(['OffereMaster','OffereMaster.Vendor'])->where('id',$request->offere_id)->first();
          $order = new  Order();
          $order->customer_id = Auth::user()->userType->id;
          $order->offere_id   = $request->offere_id;
          $order->vendor_id   = $get_offere_detail->offeremaster->vendor_id;
          $order->product_id  = $get_offere_detail->offeremaster->product_id;
          $order->cash_price  = $get_offere_detail_for_cash->cash_price;
          $order->order_date  = $CurrentDate;
          $order->place_order = 'insto';
          $order->status      = 'pending';
          $order->save();
          $status = true;
          $errMsg= 'Order Saved Successfully';
      }
         return response()->json([
         'status'    => $status,
         'message'    => $errMsg
          ]);      
   }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use App\Order;
use Session;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Session::get('checkorderlink') == 'total_orders'){
            $orders  = Order::with(['Customer','OffereDetail.OffereMaster.Vendor','OffereDetail.OffereMaster.Product'])->get();
        }
        else if(Session::get('checkorderlink') == 'total_new_orders'){
            $orders  = Order::with(['Customer','OffereDetail.OffereMaster.Vendor','OffereDetail.OffereMaster.Product'])->where('status','pending')->get();
        }
        else{
            $orders  = Order::with(['Customer','OffereDetail.OffereMaster.Vendor','OffereDetail.OffereMaster.Product'])->get();
        }
        return view('admin.Order.index', compact('orders'));
    }
    public function changeorderstatus(Request $request)
    {
        $status = false;
        $order = Order::where('id',$request->id)->first();
        if($order){
            $order->status = $request->value;
            $order->save();
            $status = true;
        }
        return response()->json( array('status' => $status ));
    }
}

resources/views/admin/Order/create.blade.php
@extends('adminlte::page')
@section('title', 'Add Owner')
@section('content_header')
    <h1>Add New Owner</h1>
    <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
    <div class="clearfix"></div>

@endsection
@section('content')
    <div class="box">
        <div class="box-header">
        </div>
        <form action="{{ route('admin.owner.store') }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('first_name') ? 'has-error' : '' }}">
                            <label>First Name <span>*</span></label>
                            <input type="text" name="first_name" class="form-control" value="{{ old('first_name') }}">
                             @if($errors->has('first_name'))
                                <span class="help-block text-danger">{{ $errors->first('first_name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('last_name') ? 'has-error' : '' }}">
                            <label>Last Name <span>*</span></label>
                            <input type="text" name="last_name" class="form-control" value="{{ old('last_name') }}">
                             @if($errors->has('last_name'))
                                <span class="help-block text-danger">{{ $errors->first('last_name') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                         <label for="title">Profile Image <span>*</span></label>
                           <div class="input-group image-preview">
                             <span class="input-group-btn">
                              <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                              <span class="glyphicon glyphicon-remove"></span> Clear
                              </button>
                              <div class="btn btn-default image-preview-input">
                               <span class="glyphicon glyphicon-folder-open"></span>
                               <span class="image-preview-input-title">Browse</span>
                               <input type="file" accept="image/png, image/jpeg, image/gif, image/jpg" name="picture_path" required=""/>
                            </div>
                             </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                            <label>Email <span>*</span></label>
                            <input type="text" name="email" class="form-control" value="{{ old('email') }}">
                             @if($errors->has('email'))
                                <span class="help-block text-danger">{{ $errors->first('email') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                            <label>Password <span>*</span> </label>
                            <input type="password" name="password" class="form-control" value="{{ old('password') }}">
                             @if($errors->has('password'))
                                <span class="help-block text-danger">{{ $errors->first('password') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : '' }}">
                            <label>Confirm Password <span>*</span> </label>
                            <input type="password" name="password_confirmation" class="form-control" value="{{ old('password_confirmation') }}">
                             @if($errors->has('password_confirmation'))
                                <span class="help-block text-danger">{{ $errors->first('password_confirmation') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('primary_phone_number') ? 'has-error' : '' }}">
                            <label>Primary Phone Number <span>*</span></label>
                            <input type="text" name="primary_phone_number" class="form-control" value="{{ old('primary_phone_number') }}">
                             @if($errors->has('primary_phone_number'))
                                <span class="help-block text-danger">{{ $errors->first('primary_phone_number') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('secondary_phone_number') ? 'has-error' : '' }}">
                            <label>Secondary Phone Number </label>
                            <input type="text" name="secondary_phone_number" class="form-control" value="{{ old('secondary_phone_number') }}">
                             @if($errors->has('secondary_phone_number'))
                                <span class="help-block text-danger">{{ $errors->first('secondary_phone_number') }}</span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group {{ $errors->has('postal_address') ? 'has-error' : '' }}">
                            <label>Postal Address </label>
                            <input type="text" name="postal_address" class="form-control" value="{{ old('postal_address') }}">
                             @if($errors->has('postal_address'))
                                <span class="help-block text-danger">{{ $errors->first('postal_address') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group {{ $errors->has('base_address') ? 'has-error' : '' }}">
                            <label>Base Address <span>*</span></label>
                            <input type="text" name="base_address" class="form-control" value="{{ old('base_address') }}">
                             @if($errors->has('base_address'))
                                <span class="help-block text-danger">{{ $errors->first('base_address') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer text-center">
                <button type="submit" class="btn btn-primary btnSubmit">Create</button>
            </div>
        </form>
    </div>
@endsection

@push('js')
<script type="text/javascript">


  $(document).on('click', '#close-preview', function(){ 
    $('.image-preview').popover('hide');
    // Hover befor close the preview
    $('.image-preview').hover(
      function () {
         $('.image-preview').popover('show');
      }, 
       function () {
         $('.image-preview').popover('hide');
      }
    );    
  });

  $(function() {
      // Create the close button
      var closebtn = $('<button/>', {
          type:"button",
          text: 'x',
          id: 'close-preview',
          style: 'font-size: initial;',
      });
      closebtn.attr("class","close pull-right");
      // Set the popover default content
      $('.image-preview').popover({
          trigger:'manual',
          html:true,
          title: "<strong>Preview</strong>"+$(closebtn)[0].outerHTML,
          content: "There's no image",
          placement:'bottom'
      });
      // Clear event
      $('.image-preview-clear').click(function(){
          $('.image-preview').attr("data-content","").popover('hide');
          $('.image-preview-filename').val("");
          $('.image-preview-clear').hide();
          $('.image-preview-input input:file').val("");
          $(".image-preview-input-title").text("Browse"); 
      }); 
      // Create the preview image
      $(".image-preview-input input:file").change(function (){     
          var img = $('<img/>', {
              id: 'dynamic',
              width:250,
              height:200
          });      
          var file = this.files[0];
          var reader = new FileReader();
          // Set preview image into the popover data-content
          reader.onload = function (e) {
              $(".image-preview-input-title").text("Change");
              $(".image-preview-clear").show();
              $(".image-preview-filename").val(file.name);            
              img.attr('src', e.target.result);
              $(".image-preview").attr("data-content",$(img)[0].outerHTML).popover("show");
          }        
          reader.readAsDataURL(file);
      });  
  });
</script>
@endpush

resources/views/admin/Order/show.blade.php
@extends('adminlte::page')
@section('title', 'Vendor')
@section('content_header')
    <h1>Vendor</h1>
    <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
    <div class="clearfix"></div>
@endsection
@section('content')
    <div class="box">
        <div class="box-header">
        </div>
            <div class="box-body">
              <div class="row">
                  <div col-md-12>
                      <input type="hidden" id="txtvendorid" value="{{$vendor->id}}">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th>First Name</th>
                                <td>{{$vendor->first_name}}</td>
                            </tr>
                            <tr>
                                <th>Last Name</th>
                                <td>{{$vendor->last_name}}</td>
                            </tr>
                            <tr>
                                <th>Company Name</th>
                                <td>{{$vendor->company_name}}</td>
                            </tr>
                            <tr>
                                <th>Designation</th>
                                <td>{{$vendor->designation}}</td>
                            </tr>
                            <tr>
                                <th>Email</th>
                                <td>{{$vendor->user->email}}</td>
                            </tr>
                            <tr>
                                <th>Secondary Phone Number</th>
                                <td>{{$vendor->secondary_phone_number}}</td>
                            </tr>
                            <tr>
                                <th>Primary Phone Number</th>
                                <td>{{$vendor->primary_phone_number}}</td>
                            </tr>
                            <tr>
                                <th>Business Address</th>
                                <td>{{$vendor->business_address}}</td>
                            </tr>
                            <tr>
                                <th>Cnic</th>
                                <td>{{$vendor->cnic}}</td>
                            </tr>
                            <tr>
                                <th>Base Address</th>
                                <td>{{$vendor->base_address}}</td>
                            </tr>
                            <tr>
                                <th>Picture Path</th>
                                <td><img src="{{$vendor->picture_path}}"></td>
                            </tr>
                            <tr>
                                <th>Cnic Picture Path</th>
                                <td>
                                    <img src="{{$vendor->cnic_front_img_path}}">
                                    @if($vendor->cnic_back_img_path!=null)
                                    <img src="{{$vendor->cnic_back_img_path}}">
                                    @endif
                                    </td>
                            </tr>
                            <tr>
                                <th>Verfication Status</th>
                                <td><select id="SelectVerifyStatusChange"><option value="Verfied" {{$vendor->verfication_status=="Verfied"?'selected':''}}>Verfied</option><option value="Unverfied" {{$vendor->verfication_status=="Unverfied"?'selected':''}}>Unverfied</option></select>&nbsp;<button type="button" class="btn btn-primary btn-xs" id="btnVerificationStatusChange">Change Status</button></td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td><select id="SelectStatusChange"><option value="true" {{$vendor->status==1?'selected':''}}>Active</option><option value="false" {{$vendor->status==0?'selected':''}}>Deactive</option></select>&nbsp;<button type="button" class="btn btn-primary btn-xs" id="btnStatusChange">Change Status</button></td>
                            </tr>
                        </tbody>
                    </table>
                  </div>
              </div>
      </div>
    </div>
@endsection
@push('js')
<script type="text/javascript">
   $.ajaxSetup({
            headers: {
            'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        });
    $("#btnStatusChange").click(function (){
        $.ajax({
                url: "{{ route('changestatus') }}",
               type: 'POST',
               data : { id : $("#txtvendorid").val() ,status: $("#SelectStatusChange").val()},
               success: function(response){
                    if(response.status == 'success'){
                        toastr['success']("Vendor Status Change Successfully.");
                    }else{
                        toastr['error']("Something went wrong.");
                    }
               },
               error: function(error){
                   toastr['error']("Something went wrong.");
               }

            });
         });

         $("#btnVerificationStatusChange").click(function (){
        $.ajax({
                url: "{{ route('changevarification') }}",
               type: 'POST',
               data : { id : $("#txtvendorid").val() ,verfication_status: $("#SelectVerifyStatusChange").val()},
               success: function(response){
                    if(response.status == 'success'){
                        toastr['success']("Vendor Verfication Status Change Successfully.");
                    }else{
                        toastr['error']("Something went wrong.");
                    }
               },
               error: function(error){
                   toastr['error']("Something went wrong.");
               }

            });
         });
</script>
@endpush