routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Web\HomeController@index')->name('web.home');

Route::post('/websearchproduct', 'Web\HomeController@websearchproduct')->name('websearchproduct');

Route::get('/category/{category_slug}', 'Web\CategoryController@index')->name('category');

Route::post('load/featureandcategory', 'Web\HomeController@loadfeatureandcategory')->name('load.featureandcategory');


Route::post('/store', 'Web\HomeController@store')->name('store');

Route::post('load/category', 'Web\HomeController@loadcategory')->name('load.category');

Route::post('load/featureandcategoryforcategorypage', 'Web\CategoryController@loadfeatureandcategoryforcategorypage')->name('load.featureandcategoryforcategorypage');

Route::post('load/product', 'Web\CategoryController@loadproduct')->name('load.product');

Route::post('load/filter/product', 'Web\CategoryController@loadfilterproduct')->name('load.filter.product');

Route::get('/product/{product_slug}', 'Web\ProductController@index')->name('product');

Route::post('load/productbylcation', 'Web\ProductController@loadproductbylcation')->name('load.productbylcation');

Route::post('load/offerebysort', 'Web\ProductController@loadofferebysort')->name('load.offerebysort');

Route::post('load/offerebyfilter', 'Web\ProductController@loadofferebyfilter')->name('load.offerebyfilter');

Route::post('load/moreoffere', 'Web\ProductController@loadmoreoffere')->name('load.moreoffere');

Route::get('/signup', 'Web\RegisterController@index')->name('signup');

Route::get('/login', 'Web\LoginController@index')->name('web.login');

Route::post('/login/login', 'Web\LoginController@login')->name('web.login.login');

Route::post('/login/loginbyemail', 'Web\LoginController@loginbyemail')->name('web.login.loginbyemail');

Route::post('/login/logout', 'Web\LoginController@logout')->name('web.login.logout');

Route::get('/brand/{brand_slug}', 'Web\BrandController@index')->name('brand');

Route::post('load/featureandbrandforbrandpage', 'Web\BrandController@loadfeatureandbrandforbrandpage')->name('load.featureandbrandforbrandpage');

Route::post('load/brandwiseproduct', 'Web\BrandController@loadbrandwiseproduct')->name('load.brandwiseproduct');

Route::post('adddeletewishlist', 'Web\WishListController@adddeletewishlist')->name('adddeletewishlist');

Route::get('/subcategory/{subcategory_slug}', 'Web\SubCategoryController@index')->name('subcategory');

Route::post('load/featureandproductforsubcategorypage', 'Web\SubCategoryController@loadfeatureandproductforsubcategorypage')->name('load.featureandproductforsubcategorypage');

Route::post('load/subcategory/product', 'Web\SubCategoryController@loadsubcategoryproduct')->name('load.subcategory.product');

Route::post('load/subcategory/filter/product', 'Web\SubCategoryController@loadsubcategoryfilterproduct')->name('load.subcategory.filter.product');

Route::get('/dashboard', 'Web\DashboardController@index')->name('web.dashboard');

Route::get('/vendor/{id}', 'Web\VendorController@index')->name('web.vendor');

Route::post('load/featureandproductforvendorpage', 'Web\VendorController@loadfeatureandproductforvendorpage')->name('load.featureandproductforvendorpage');

Route::post('load/vendorwiseproduct', 'Web\VendorController@loadvendorwiseproduct')->name('load.vendorwiseproduct');

Route::get('/search/{search_slug}', 'Web\SearchController@index')->name('web.search');

Route::post('load/featureandproductforsearchpage', 'Web\SearchController@loadfeatureandproductforsearchpage')->name('load.featureandproductforsearchpage');

Route::post('load/searchwiseproduct', 'Web\SearchController@loadsearchwiseproduct')->name('load.searchwiseproduct');

Route::post('getroute', 'Web\HomeController@getroute')->name('getroute');

Route::post('order', 'Web\ProductController@order')->name('order');

Route::post('web/sendotp', 'Web\RegisterController@sendotp')->name('web.sendotp');

Route::post('web/checkotp', 'Web\RegisterController@checkotp')->name('web.checkotp');

Route::post('web/customerregistration', 'Web\RegisterController@customerregistration')->name('web.customerregistration');

Route::post('web/subarea', 'Web\RegisterController@subarea')->name('web.subarea');

Route::get('web/contact-us', 'Web\HomeController@contactus')->name('web.contactus');

Route::get('web/about-us', 'Web\HomeController@aboutus')->name('web.aboutus');

Route::get('web/faq', 'Web\HomeController@faq')->name('web.faq');

Route::get('web/privacy-policy', 'Web\HomeController@privacy')->name('web.privacy-policy');

Route::get('web/term-conditions', 'Web\HomeController@termandcondition')->name('web.term-conditions');

Route::get('web/why-buy-from-us', 'Web\HomeController@whybuyfromus')->name('web.why-buy-from-us');

Route::post('web/customerprofileupdate', 'Web\RegisterController@customerprofileupdate')->name('web.customerprofileupdate');

Route::get('/forget', 'Web\ForgetController@index')->name('web.forget');

Route::post('web/forget/sendotp', 'Web\ForgetController@forgetsendotp')->name('web.forget.sendotp');

Route::post('web/.forget/checkotp', 'Web\ForgetController@forgetcheckotp')->name('web.forget.checkotp');

Route::post('web/forget/password', 'Web\ForgetController@customerforgetPassword')->name('web.forget.customerforgetPassword');

Route::get('web/contact-us', 'Web\ContactUsController@contactus')->name('web.contactus');

Route::post('web/contact-us/send', 'Web\ContactUsController@store')->name('web.contactus.send');

Route::get('admin/', function () {
    return view('auth.login');
});
Route::group(['prefix' => 'admin'], function () {
    Auth::routes();
});



//Auth::routes();
Route::get('auth/redirect/{provider}', 'Auth\FacebookLoginController@redirect');
Route::get('callback/{provider}', 'Auth\FacebookLoginController@callback');

Route::post('/sendOTP', 'Auth\LoginController@sendOTP')->name('sendOTP');

Route::middleware(['auth','disablepreventback'])->group(function () {
    
 Route::get('admin/home', 'Admin\DashboardController@index')->name('home');

  Route::resource('/admin/brand', 'Admin\BrandController', [ 'names' => [
            'index'    => 'admin.brand.index',
            'create'   => 'admin.brand.create',
            'store'    => 'admin.brand.store',
            'edit'     => 'admin.brand.edit',
            'update'   => 'admin.brand.update',
            'destroy'  => 'admin.brand.destroy',
        ]
    ]);

  Route::resource('/admin/InfoGraphic', 'Admin\InfoGraphicController', [ 'names' => [
            'index'    => 'admin.InfoGraphic.index',
            'create'   => 'admin.InfoGraphic.create',
            'store'    => 'admin.InfoGraphic.store',
            'edit'     => 'admin.InfoGraphic.edit',
            'update'   => 'admin.InfoGraphic.update',
            'destroy'  => 'admin.InfoGraphic.destroy',
        ]
    ]);

  Route::resource('/admin/ads', 'Admin\AdsController', [ 'names' => [
            'index'    => 'admin.ads.index',
            'create'   => 'admin.ads.create',
            'store'    => 'admin.ads.store',
            'edit'     => 'admin.ads.edit',
            'update'   => 'admin.ads.update',
            'destroy'  => 'admin.ads.destroy',
        ]
    ]);

  Route::resource('/admin/categories', 'Admin\CategoryController', [ 'names' => [
            'index'    => 'admin.categories.index',
            'create'   => 'admin.categories.create',
            'store'    => 'admin.categories.store',
            'edit'     => 'admin.categories.edit',
            'update'   => 'admin.categories.update',
            'destroy'  => 'admin.categories.destroy',
        ]
    ]);

  Route::resource('/admin/subcategories', 'Admin\SubCategoryController', [ 'names' => [
            'index'    => 'admin.subcategories.index',
            'create'   => 'admin.subcategories.create',
            'store'    => 'admin.subcategories.store',
            'edit'     => 'admin.subcategories.edit',
            'update'   => 'admin.subcategories.update',
            'destroy'  => 'admin.subcategories.destroy',
        ]
    ]);

  Route::resource('/admin/product', 'Admin\ProductController', [ 'names' => [
            'index'    => 'admin.product.index',
            'create'   => 'admin.product.create',
            'store'    => 'admin.product.store',
            'edit'     => 'admin.product.edit',
            'update'   => 'admin.product.update',
            'destroy'  => 'admin.product.destroy',
        ]
    ]);
  Route::post('/subcategorybyid', 'Admin\ProductController@subcategorybyid')->name('subcategorybyid');
  Route::post('/keyfeaturebysubid', 'Admin\ProductController@keyfeaturebysubid')->name('keyfeaturebysubid');
  Route::post('/deletegalleryimage', 'Admin\ProductController@deletegalleryimage')->name('deletegalleryimage');
  Route::post('/changenewarrival', 'Admin\ProductController@changenewarrival')->name('changenewarrival');
  Route::post('/changehotproduct', 'Admin\ProductController@changehotproduct')->name('changehotproduct');

  Route::resource('/admin/keyfeature', 'Admin\KeyFeatureController', [ 'names' => [
            'index'    => 'admin.keyfeature.index',
            'create'   => 'admin.keyfeature.create',
            'store'    => 'admin.keyfeature.store',
            'edit'     => 'admin.keyfeature.edit',
            'update'   => 'admin.keyfeature.update',
            'destroy'  => 'admin.keyfeature.destroy',
        ]
    ]);

  Route::resource('/admin/package', 'Admin\PackageController', [ 'names' => [
            'index'    => 'admin.package.index',
            'create'   => 'admin.package.create',
            'store'    => 'admin.package.store',
            'edit'     => 'admin.package.edit',

app/Owner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
    public function getPicturePathAttribute($path)
    {
        if($path){
            return asset(str_replace('public/', 'storage/', $path));
            }
            else{
                return null;
            }
    }

    public function User()
    {
       return $this->belongsTo(User::Class);
    }
}

resources/views/web/vendor_page_partial_view/feature_deal.blade.php
<div class="featured">
  <div class="container">
    <div class="boxMain">
      <div class="boxHeader">
        <h2>Featured Deals</h2>
      </div>
      <div class="boxBody">
        <div class="owl-carousel" id="featuredDeals">
        @foreach ($get_featured_product as $feature_product)
          <div class="item">
            <div class="productMain">
              <div class="productImage">
                <img src="{{$feature_product->offeremaster->product->productimage[0]->productresizeimage[3]->product_resize_image_path}}" alt="">
                <div class="overlay">
                  @if(Auth::check()==true && Auth::user()->user_type == "client")
                  <a href="javascript:void(0)" onclick="product_wishlist('{{$feature_product->id}}')"><i class="{{$feature_product->wishlist!=null ? 'fas' : 'far' }} fa-heart wishlist{{$feature_product->id}}"></i></a>
                  @else
                  <a href="javascript:void(0)" onclick="login()"><i class="far fa-heart"></i></a>
                  @endif
                  <a href="{{ route('product', $feature_product->offeremaster->product->product_slug)}}"  class="btn btnDetails" >View Details</a>
                </div>
              </div>
              <div class="productDesc">
                <h3 class="uppercase">{{ trans($feature_product->offeremaster->product->product_name)}}</h3>
                <h5 class="uppercase">By: {{ trans($feature_product->offeremaster->vendor->company_name)}}</h5>
                <h4>{{number_format($feature_product->installment)}} <span>Rs. / month</span></h4>
              </div>
            </div>
          </div>
          @endforeach
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/web/vendor_page_partial_view/product.blade.php
@if(count($load_more_product) > 0)
@foreach ($load_more_product as $product)
<input type="hidden" name="product_id" value="{{$product->id}}">
        <div class="col-md-3 col-sm-3 col-xs-12 noPadd">
          <div class="productMain">
            <div class="productImage">
              @if( !$product->productimage->isEmpty())
              <img src="{{$product->productimage[0]->productresizeimage[3]->product_resize_image_path}}" alt="{{$product->productimage[0]->productresizeimage[3]->alt}}">
              @else
              <img src="{{ asset("images/web-images/product.png")}}" alt="">
              @endif
              <div class="overlay">
                <a href="{{route('product', $product->product_slug)}}"  class="btn btnDetails">View Details</a>
              </div>
            </div>
            <div class="productDesc">
              <h3 class="uppercase">{{$product->product_name}}</h3>
              @if( $product->getminoffere!=null)
              <h5>Starting from</h5>
              <h4>{{number_format($product->getminoffere)}} <span>/ month</span></h4>
              @else
              <h5>&nbsp;</h5>
              <h4>&nbsp; <span></span></h4>
              @endif
            </div>
          </div>
        </div>
@endforeach
@else
@if(count($get_vendor_product)>0)
@foreach ($get_vendor_product as $product)
<input type="hidden" name="product_id" value="{{$product->id}}">
        <div class="col-md-3 col-sm-3 col-xs-12 noPadd">
          <div class="productMain">
            <div class="productImage">
              @if( !$product->productimage->isEmpty())
              <img src="{{$product->productimage[0]->productresizeimage[3]->product_resize_image_path}}" alt="{{$product->productimage[0]->productresizeimage[3]->alt}}">
              @else
              <img src="{{ asset("images/web-images/product.png")}}" alt="">
              @endif
              <div class="overlay">
                <a href="{{route('product', $product->product_slug)}}"  class="btn btnDetails">View Details</a>
              </div>
            </div>
            <div class="productDesc">
              <h3 class="uppercase">{{$product->product_name}}</h3>
              @if( $product->getminoffere!=null)
              <h5>Starting from</h5>
              <h4>{{number_format($product->getminoffere)}} <span>Rs. / month</span></h4>
              @else
              <h5>&nbsp;</h5>
              <h4>&nbsp; <span></span></h4>
              @endif
            </div>
          </div>
        </div>
@endforeach
@else
@endif
@endif

resources/views/web/vendor_page_partial_view/vendor.blade.php
@if(!empty($vendor))
      <div class="boxHeader">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <h2>{{$vendor->company_name}}</h2>
          </div>
        </div>
      </div>
      <div class="boxBody">
      <div class="row">
        <div class="col-md-3">
          @include('web.vendor_page_partial_view.vendor_detail')
        </div> 
      <div class="col-md-9" id="loadnewproduct">
        @include('web.vendor_page_partial_view.product')			
      </div>
    </div>
    </div>    
@else   
@endif

resources/views/web/vendor_page_partial_view/vendor_detail.blade.php
<div class="brandInformation">
    <div class="brandLogo">
        @if($vendor->picture_path==null)
        <img src="{{ asset('images/web-images/qaziSm.png') }}" alt="">

        <img src="{{$vendor->picture_path}}" alt="">
        @endif
    </div>
    <div class="brandDesc">
        <h3>{{$vendor->first_name??"".''.$vendor->last_name??""}}</h3>
        <h2>Description</h2>
        <p>{{$vendor->business_address??""}}</p>
    </div>
</div>